---
driver:
  name: vagrant
  provider: vmware_fusion
  #box: opscode-centos-6.5-vmware
  box: opscode-centos-6.5
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  # require_chef_omnibus: latest # will install on each run
  require_chef_omnibus: 11.8.2


platforms:
- name: centos-6.5

suites:
- name: learnchef
