---
driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    memory: 512

provisioner:
  name: chef_solo
  # require_chef_omnibus: latest # will install on each run
  require_chef_omnibus: 11.8.2


platforms:
- name: centos-6.5

suites:
- name: learnchef
