---
driver:
  name: vagrant
  provider: vmware_fusion
  box: opscode-centos-6.5
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  # cookbook_path: ./cookbooks
  # require_chef_omnibus: latest # will install on each run
  require_chef_omnibus: 11.16.4


platforms:
- name: centos-6.5

suites:
- name: default
  run_list:
    - "recipe[tci]"
