---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[chef_user::default]
    attributes:
      authorization:
        sudo:
          users: ["vagrant", "chef"]
          passwordless: true
